site_name: Apunts Material

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro

    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo claro

nav:
  - Inici: index.md
  - Grammar:
      - Present Simple: tema1.md
      - Present Continuous: tema2.md

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js

site_url: https://MissBfrances.github.io/apunts-material/